# Generated by github.com/davyxu/tabtoy
# Version: 2.9.1
# Modify by nuyan
chapter_section_hero_conf: [
	{SectionID: 101, Seat: 0, HeroID: 1001, HPMax: 3, HP: 3, Level: 1, SkillID:[ 1 ], StoneSkillID:[ 401 ], InitCardCount: 3 }, 
	{SectionID: 101, Seat: 1, HeroID: 1002, HPMax: 3, HP: 3, Level: 1, SkillID:[ 2 ], StoneSkillID:[ 401 ], InitCardCount: 4 }, 
	{SectionID: 101, Seat: 2, HeroID: 1003, HPMax: 3, HP: 3, Level: 1, SkillID:[ 3 ], StoneSkillID:[ 401 ], InitCardCount: 4 }
]

chapter_section_conf: [
	{SectionID: 101, PreSectionID: 100, NeedEnergy: 1, SeatNum: 3, CardHeap: 2, InitParm: 2, Star2Condition: { DiedCount: 4 }, ExpReward: 10, CoinReward: 100, RandomDropGroupID: 1000 }
]

chapter_conf: [
	{ChapterID: 1, Name: "桃园结义", UnlockStarNum: 10, SectionList:[ { SectionImageID: 1 }, { SectionImageID: 2 } ], Box1StarNum: 2, Box2StarNum: 5, Box3StarNum: 10 }
]

ItemTest2: [
	{ID: 1, Hello: 1002 }, 
	{ID: 2, Hello: 2001 }, 
	{ID: 1, Hello: 1002 }, 
	{ID: 2, Hello: 2001 }
]

