# Generated by github.com/davyxu/tabtoy
# Version: 2.9.1
Item: [
	{ID: 1, UpgradeCost: 100 }, 
	{ID: 2, UpgradeCost: 200 }, 
	{SectionID: 1, Age: 100 }, 
	{SectionID: 2, Age: 200 }
]

ItemTest2: [
	{ID: 1, Hello: 1002 }, 
	{ID: 2, Hello: 2001 }
]

